sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 950501
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALIYUN_OSS_ACCESS_KEY_ID:placeholder}
    access-key-secret: ${ALIYUN_OSS_ACCESS_KEY_SECRET:placeholder}
    bucket-name: changing-java
  redis:
    host: localhost
    port: 6379
  wechat:
    appid: wx36e9e912ec952027
    secret: 56dd99ca8a924306065b51da6d49b0f6

